// AUTO-GENERATED from UeCampus_SEO_Keyword_Map_FULL.xlsx (Programme Pages tab).
// Per-course SEO from the keyword map. Regenerate rather than hand-editing.
export type CourseSeo = { title: string; description: string; keywords: string; h1: string };

export const courseSeoOverrides: Record<string, CourseSeo> = {
  "bachelor-of-arts-in-accountancy-and-finance-eie-european-business-school": {
    title: "Bachelor of Arts in Accountancy and Finance | eie | UeCampus",
    description: "Accredited European Bachelor of Arts in Accountancy and Finance delivered 100% online through eie European Business School. Flexible, affordable",
    keywords: "online bachelor of arts in accountancy and finance, bachelor of arts in accountancy and finance eie european business school, european degree online, MQF accredited degree",
    h1: "Bachelor of Arts in Accountancy and Finance - eie European Business School (Online)",
  },
  "bachelor-of-arts-in-business-managment---eie-european-business-school": {
    title: "Bachelor of Arts in Business Managment | eie | UeCampus",
    description: "Accredited European Bachelor of Arts in Business Managment delivered 100% online through eie European Business School. Flexible, affordable, globally",
    keywords: "online bachelor of arts in business managment, bachelor of arts in business managment eie european business school, european degree online, MQF accredited degree",
    h1: "Bachelor of Arts in Business Managment - eie European Business School (Online)",
  },
  "bachelor-of-business-administration-bba": {
    title: "Online Bachelor of Business Administration BBA | UeCampus",
    description: "Study a recognised Bachelor of Business Administration BBA 100% online with UeCampus. Flexible schedules, monthly instalments and full tutor support.",
    keywords: "online bachelor of business administration bba, recognised bachelor of business administration bba online, bachelor of business administration bba distance learning, affordable bachelor of business administration bba",
    h1: "Bachelor of Business Administration BBA (Online)",
  },
  "bachelors-in-accounting": {
    title: "Online Bachelors in Accounting | Recognised | UeCampus",
    description: "Study a recognised Bachelors in Accounting 100% online with UeCampus. Flexible schedules, monthly instalments and full tutor support. Sept 2026 intake",
    keywords: "online bachelors in accounting, recognised bachelors in accounting online, bachelors in accounting distance learning, affordable bachelors in accounting",
    h1: "Bachelors in Accounting (Online)",
  },
  "bachelors-in-data-analytics": {
    title: "Online Bachelors in Data Analytics | Recognised | UeCampus",
    description: "Study a recognised Bachelors in Data Analytics 100% online with UeCampus. Flexible schedules, monthly instalments and full tutor support. Sept 2026",
    keywords: "online bachelors in data analytics, recognised bachelors in data analytics online, bachelors in data analytics distance learning, affordable bachelors in data analytics",
    h1: "Bachelors in Data Analytics (Online)",
  },
  "bachelors-in-entrepreneurship": {
    title: "Online Bachelors in Entrepreneurship | Recognised | UeCampus",
    description: "Study a recognised Bachelors in Entrepreneurship 100% online with UeCampus. Flexible schedules, monthly instalments and full tutor support. Sept 2026",
    keywords: "online bachelors in entrepreneurship, recognised bachelors in entrepreneurship online, bachelors in entrepreneurship distance learning, affordable bachelors in entrepreneurship",
    h1: "Bachelors in Entrepreneurship (Online)",
  },
  "bachelors-of-arts-in-tourism-and-hospitality-management-eie-european-business-school": {
    title: "Bachelors of Arts in Tourism and Hospitality Management | ei",
    description: "Accredited European Bachelors of Arts in Tourism and Hospitality Management delivered 100% online through eie European Business School. Flexible",
    keywords: "online bachelors of arts in tourism and hospitality management, bachelors of arts in tourism and hospitality management eie european business school, european degree online, MQF accredited degree",
    h1: "Bachelors of Arts in Tourism and Hospitality Management - eie European Business School (Online)",
  },
  "bba-business-management-eie": {
    title: "Online BBA Business Management | eie Malta | UeCampus",
    description: "Accredited European BBA Business Management delivered 100% online through eie European Business School. Flexible, affordable, globally recognised.",
    keywords: "online bba business management, bba business management eie european business school, european degree online, MQF accredited degree",
    h1: "BBA Business Management - eie European Business School (Online)",
  },
  "bba-finance-walsh": {
    title: "Online BBA Finance | Walsh College USA | UeCampus",
    description: "Earn an accredited BBA Finance 100% online from Walsh College USA (HLC & ACBSP accredited). Flexible study, monthly instalments, Sept 2026 intake.",
    keywords: "online bba finance, bba finance walsh college, accredited american bba finance online, US degree online",
    h1: "BBA Finance - Walsh College, USA (Online)",
  },
  "bba-human-resource-management-ppa": {
    title: "Online BBA Human Resource Management | PPA Paris | UeCampus",
    description: "Study an accredited BBA Human Resource Management online with PPA Business School Paris. No GMAT, flexible payments, finish in 12-18 months. Enrolling",
    keywords: "online bba human resource management, bba human resource management ppa business school, french business school bba human resource management online, affordable bba human resource management",
    h1: "BBA Human Resource Management - PPA Business School Paris (Online)",
  },
  "bba-human-resource-management-walsh": {
    title: "BBA Human Resource Management Online | Walsh | UeCampus",
    description: "Earn an accredited BBA Human Resource Management 100% online from Walsh College USA (HLC & ACBSP accredited). Flexible study, monthly instalments, Sept",
    keywords: "online bba human resource management, bba human resource management walsh college, accredited american bba human resource management online, US degree online",
    h1: "BBA Human Resource Management - Walsh College, USA (Online)",
  },
  "bba-in-general-business": {
    title: "Online BBA in General Business | Recognised | UeCampus",
    description: "Study a recognised BBA in General Business 100% online with UeCampus. Flexible schedules, monthly instalments and full tutor support. Sept 2026 intake",
    keywords: "online bba in general business, recognised bba in general business online, bba in general business distance learning, affordable bba in general business",
    h1: "BBA in General Business (Online)",
  },
  "bba-international-business-ppa": {
    title: "Online BBA International Business | PPA Paris | UeCampus",
    description: "Study an accredited BBA International Business online with PPA Business School Paris. No GMAT, flexible payments, finish in 12-18 months. Enrolling for",
    keywords: "online bba international business, bba international business ppa business school, french business school bba international business online, affordable bba international business",
    h1: "BBA International Business - PPA Business School Paris (Online)",
  },
  "bba-international-business-walsh": {
    title: "Online BBA International Business | Walsh College | UeCampus",
    description: "Earn an accredited BBA International Business 100% online from Walsh College USA (HLC & ACBSP accredited). Flexible study, monthly instalments, Sept 2026",
    keywords: "online bba international business, bba international business walsh college, accredited american bba international business online, US degree online",
    h1: "BBA International Business - Walsh College, USA (Online)",
  },
  "bba-marketing-ppa": {
    title: "Online BBA Marketing | PPA Paris | UeCampus",
    description: "Study an accredited BBA Marketing online with PPA Business School Paris. No GMAT, flexible payments, finish in 12-18 months. Enrolling for September 2026.",
    keywords: "online bba marketing, bba marketing ppa business school, french business school bba marketing online, affordable bba marketing",
    h1: "BBA Marketing - PPA Business School Paris (Online)",
  },
  "bba-marketing-walsh": {
    title: "Online BBA Marketing | Walsh College USA | UeCampus",
    description: "Earn an accredited BBA Marketing 100% online from Walsh College USA (HLC & ACBSP accredited). Flexible study, monthly instalments, Sept 2026 intake.",
    keywords: "online bba marketing, bba marketing walsh college, accredited american bba marketing online, US degree online",
    h1: "BBA Marketing - Walsh College, USA (Online)",
  },
  "bba-walsh": {
    title: "Online BBA | Walsh College USA | UeCampus",
    description: "Earn an accredited BBA 100% online from Walsh College USA (HLC & ACBSP accredited). Flexible study, monthly instalments, Sept 2026 intake.",
    keywords: "online bba, bba walsh college, accredited american bba online, US degree online",
    h1: "BBA - Walsh College, USA (Online)",
  },
  "bsc-cyber-security-walsh": {
    title: "Online BSc Cyber Security | Walsh College USA | UeCampus",
    description: "Earn an accredited BSc Cyber Security 100% online from Walsh College USA (HLC & ACBSP accredited). Flexible study, monthly instalments, Sept 2026 intake.",
    keywords: "online bsc cyber security, bsc cyber security walsh college, accredited american bsc cyber security online, US degree online",
    h1: "BSc Cyber Security - Walsh College, USA (Online)",
  },
  "bsc-in-artificial-intelligence--machine-learning": {
    title: "BSc in Artificial Intelligence Machine Learning | UeCampus",
    description: "Study a recognised BSc in Artificial Intelligence Machine Learning 100% online with UeCampus. Flexible schedules, monthly instalments and full tutor",
    keywords: "online bsc in artificial intelligence machine learning, recognised bsc in artificial intelligence machine learning online, bsc in artificial intelligence machine learning distance learning, affordable bsc in artificial intelligence machine learning",
    h1: "BSc in Artificial Intelligence Machine Learning (Online)",
  },
  "bsc-in-data-analytics": {
    title: "Online BSc in Data Analytics | Recognised | UeCampus",
    description: "Study a recognised BSc in Data Analytics 100% online with UeCampus. Flexible schedules, monthly instalments and full tutor support. Sept 2026 intake open.",
    keywords: "online bsc in data analytics, recognised bsc in data analytics online, bsc in data analytics distance learning, affordable bsc in data analytics",
    h1: "BSc in Data Analytics (Online)",
  },
  "bsc-information-technology-walsh": {
    title: "Online BSc Information Technology | Walsh College | UeCampus",
    description: "Earn an accredited BSc Information Technology 100% online from Walsh College USA (HLC & ACBSP accredited). Flexible study, monthly instalments, Sept 2026",
    keywords: "online bsc information technology, bsc information technology walsh college, accredited american bsc information technology online, US degree online",
    h1: "BSc Information Technology - Walsh College, USA (Online)",
  },
  "dba-walsh": {
    title: "Online DBA | Walsh College USA | UeCampus",
    description: "Earn an accredited DBA 100% online from Walsh College USA (HLC & ACBSP accredited). Flexible study, monthly instalments, Sept 2026 intake.",
    keywords: "online dba, dba walsh college, accredited american dba online, US degree online",
    h1: "DBA - Walsh College, USA (Online)",
  },
  "doctor-of-business-administration-dba": {
    title: "Online DBA | Doctorate in Business Admin | UeCampus",
    description: "Earn your Doctorate in Business Administration 100% online. Recognised, research-driven and built for working executives. Enquire for Sept 2026.",
    keywords: "online DBA, doctorate of business administration online, affordable DBA, DBA distance learning",
    h1: "Doctor of Business Administration (Online)",
  },
  "doctor-of-philosophy-in-cyber-security": {
    title: "Online Doctor of Philosophy in Cyber Security | UeCampus",
    description: "Study a recognised Doctor of Philosophy in Cyber Security 100% online with UeCampus. Flexible schedules, monthly instalments and full tutor support.",
    keywords: "online doctor of philosophy in cyber security, recognised doctor of philosophy in cyber security online, doctor of philosophy in cyber security distance learning, affordable doctor of philosophy in cyber security",
    h1: "Doctor of Philosophy in Cyber Security (Online)",
  },
  "doctor-of-philosophy-in-data-analytics": {
    title: "Online Doctor of Philosophy in Data Analytics | UeCampus",
    description: "Study a recognised Doctor of Philosophy in Data Analytics 100% online with UeCampus. Flexible schedules, monthly instalments and full tutor support.",
    keywords: "online doctor of philosophy in data analytics, recognised doctor of philosophy in data analytics online, doctor of philosophy in data analytics distance learning, affordable doctor of philosophy in data analytics",
    h1: "Doctor of Philosophy in Data Analytics (Online)",
  },
  "level-2-diploma-in-business-beginners-in-cyber-security": {
    title: "Level 2 Diploma: Business Beginners in Cyber Security | UeCa",
    description: "UK Level 2 Diploma in Business Beginners in Cyber Security: Start from zero with this entry-level UK qualification. 100% online, assignment-based, with",
    keywords: "level 2 diploma in business beginners in cyber security, online business beginners in cyber security diploma UK, level 2 business beginners in cyber security course online",
    h1: "Level 2 Diploma in Business Beginners in Cyber Security (Online)",
  },
  "level-3-extended-diploma-in-it-and-data-science": {
    title: "Level 3 IT and Data Science Diploma Online | UeCampus",
    description: "UK Level 3 Diploma in IT and Data Science: Equivalent to A-Levels/Grade 12 and your bridge to university study. 100% online, no exams, flexible monthly",
    keywords: "level 3 diploma in it and data science, online it and data science diploma UK, level 3 it and data science course online",
    h1: "Level 3 Diploma in IT and Data Science (Online)",
  },
  "level-4-diploma-in-artificial-intelligence": {
    title: "Level 4 Artificial Intelligence Diploma Online | UeCampus",
    description: "UK Level 4 Diploma in Artificial Intelligence: Equivalent to the first year of a UK degree. Study 100% online with assignments only and progress towards",
    keywords: "level 4 diploma in artificial intelligence, online artificial intelligence diploma UK, level 4 artificial intelligence course online",
    h1: "Level 4 Diploma in Artificial Intelligence (Online)",
  },
  "level-5-diploma-in-artificial-intelligence": {
    title: "Level 5 Artificial Intelligence Diploma Online | UeCampus",
    description: "UK Level 5 Diploma in Artificial Intelligence: 120 Ofqual-regulated credits in deep learning, NLP and computer vision. 100% online, assignments only,",
    keywords: "level 5 diploma in artificial intelligence, online artificial intelligence diploma UK, qualifi level 5 artificial intelligence, level 5 machine learning course online",
    h1: "Level 5 Diploma in Artificial Intelligence (Online)",
  },
  "level-4-diploma-in-hospitality-and-tourism-management": {
    title: "Level 4 Diploma: Hospitality and Tourism Management | UeCamp",
    description: "UK Level 4 Diploma in Hospitality and Tourism Management: Equivalent to the first year of a UK degree. Study 100% online with assignments only and",
    keywords: "level 4 diploma in hospitality and tourism management, online hospitality and tourism management diploma UK, level 4 hospitality and tourism management course online",
    h1: "Level 4 Diploma in Hospitality and Tourism Management (Online)",
  },
  "level-7-diploma-in-accounting-and-finance": {
    title: "Level 7 Accounting and Finance Diploma Online | UeCampus",
    description: "UK Level 7 Diploma in Accounting and Finance: A masters-level UK award and affordable route to an MBA/MSc top-up. Fully online, assignment-based, no exams.",
    keywords: "level 7 diploma in accounting and finance, online accounting and finance diploma UK, level 7 accounting and finance course online",
    h1: "Level 7 Diploma in Accounting and Finance (Online)",
  },
  "level-7-diploma-in-cyber-security": {
    title: "Level 7 Cyber Security Diploma Online | UeCampus",
    description: "UK Level 7 Diploma in Cyber Security: A masters-level UK award and affordable route to an MBA/MSc top-up. Fully online, assignment-based, no exams.",
    keywords: "level 7 diploma in cyber security, online cyber security diploma UK, level 7 cyber security course online",
    h1: "Level 7 Diploma in Cyber Security (Online)",
  },
  "level-7-diploma-in-data-science": {
    title: "Level 7 Data Science Diploma Online | UeCampus",
    description: "UK Level 7 Diploma in Data Science: A masters-level UK award and affordable route to an MBA/MSc top-up. Fully online, assignment-based, no exams.",
    keywords: "level 7 diploma in data science, online data science diploma UK, level 7 data science course online",
    h1: "Level 7 Diploma in Data Science (Online)",
  },

  
  "level-7-diploma-in-health-and-social-care": {
    title: "Level 7 Health and Social Care Diploma Online | UeCampus",
    description: "UK Level 7 Diploma in Health and Social Care: A masters-level UK award and affordable route to an MBA/MSc top-up. Fully online, assignment-based, no exams.",
    keywords: "level 7 diploma in health and social care, online health and social care diploma UK, level 7 health and social care course online",
    h1: "Level 7 Diploma in Health and Social Care (Online)",
  },
  "level-7-diploma-in-hospitality-and-tourism-management": {
    title: "Level 7 Diploma: Hospitality and Tourism Management | UeCamp",
    description: "UK Level 7 Diploma in Hospitality and Tourism Management: A masters-level UK award and affordable route to an MBA/MSc top-up. Fully online",
    keywords: "level 7 diploma in hospitality and tourism management, online hospitality and tourism management diploma UK, level 7 hospitality and tourism management course online",
    h1: "Level 7 Diploma in Hospitality and Tourism Management (Online)",
  },
  "level-7-diploma-in-human-resource-management": {
    title: "Level 7 Human Resource Management Diploma Online | UeCampus",
    description: "UK Level 7 Diploma in Human Resource Management: A masters-level UK award and affordable route to an MBA/MSc top-up. Fully online, assignment-based, no",
    keywords: "level 7 diploma in human resource management, online human resource management diploma UK, level 7 human resource management course online",
    h1: "Level 7 Diploma in Human Resource Management (Online)",
  },
  "level-7-diploma-in-information-technology": {
    title: "Level 7 Information Technology Diploma Online | UeCampus",
    description: "UK Level 7 Diploma in Information Technology: A masters-level UK award and affordable route to an MBA/MSc top-up. Fully online, assignment-based, no exams.",
    keywords: "level 7 diploma in information technology, online information technology diploma UK, level 7 information technology course online",
    h1: "Level 7 Diploma in Information Technology (Online)",
  },
  
  "level-7-diploma-in-psychology": {
    title: "Level 7 Psychology Diploma Online | UeCampus",
    description: "UK Level 7 Diploma in Psychology: A masters-level UK award and affordable route to an MBA/MSc top-up. Fully online, assignment-based, no exams.",
    keywords: "level 7 diploma in psychology, online psychology diploma UK, level 7 psychology course online",
    h1: "Level 7 Diploma in Psychology (Online)",
  },
  "level-7-diploma-in-strategic-management-and-leadership": {
    title: "Level 7 Diploma: Strategic Management and Leadership | UeCam",
    description: "UK Level 7 Diploma in Strategic Management and Leadership: A masters-level UK award and affordable route to an MBA/MSc top-up. Fully online",
    keywords: "level 7 diploma in strategic management and leadership, online strategic management and leadership diploma UK, level 7 strategic management and leadership course online",
    h1: "Level 7 Diploma in Strategic Management and Leadership (Online)",
  },
  "level-7-diploma-in-strategic-marketing": {
    title: "Level 7 Strategic Marketing Diploma Online | UeCampus",
    description: "UK Level 7 Diploma in Strategic Marketing: A masters-level UK award and affordable route to an MBA/MSc top-up. Fully online, assignment-based, no exams.",
    keywords: "level 7 diploma in strategic marketing, online strategic marketing diploma UK, level 7 strategic marketing course online",
    h1: "Level 7 Diploma in Strategic Marketing (Online)",
  },
  "level-7-international-diploma-in-process-safety-management": {
    title: "Level 7 Process Safety Management Diploma Online | UeCampus",
    description: "UK Level 7 Diploma in Process Safety Management: A masters-level UK award and affordable route to an MBA/MSc top-up. Fully online, assignment-based, no",
    keywords: "level 7 diploma in process safety management, online process safety management diploma UK, level 7 process safety management course online",
    h1: "Level 7 Diploma in Process Safety Management (Online)",
  },
  "master-business-management-eie": {
    title: "Online Master Business Management | eie Malta | UeCampus",
    description: "Accredited European Master Business Management delivered 100% online through eie European Business School. Flexible, affordable, globally recognised.",
    keywords: "online master business management, master business management eie european business school, european degree online, MQF accredited degree",
    h1: "Master Business Management - eie European Business School (Online)",
  },
  "master-hospitality-tourism-eie": {
    title: "Online Master Hospitality Tourism | eie Malta | UeCampus",
    description: "Accredited European Master Hospitality Tourism delivered 100% online through eie European Business School. Flexible, affordable, globally recognised.",
    keywords: "online master hospitality tourism, master hospitality tourism eie european business school, european degree online, MQF accredited degree",
    h1: "Master Hospitality Tourism - eie European Business School (Online)",
  },
  "master-of-business-administration-mba": {
    title: "Online MBA | Recognised & Affordable | UeCampus",
    description: "Earn an accredited MBA 100% online. No GMAT, monthly instalments, 12-18 months. Choose Walsh (USA), PPA (Paris) or eie (Europe). Sept 2026 intake.",
    keywords: "online MBA, affordable online MBA, recognised MBA online, MBA without GMAT, distance learning MBA",
    h1: "Online MBA Programmes",
  },
  "master-of-business-administration-mba-eie-european-business-school": {
    title: "Master of Business Administration MBA | eie | UeCampus",
    description: "Accredited European Master of Business Administration MBA delivered 100% online through eie European Business School. Flexible, affordable, globally",
    keywords: "online master of business administration mba, master of business administration mba eie european business school, european degree online, MQF accredited degree",
    h1: "Master of Business Administration MBA - eie European Business School (Online)",
  },
  "master-of-science-in-data-analytics": {
    title: "Online Master of Science in Data Analytics | UeCampus",
    description: "Study a recognised Master of Science in Data Analytics 100% online with UeCampus. Flexible schedules, monthly instalments and full tutor support. Sept",
    keywords: "online master of science in data analytics, recognised master of science in data analytics online, master of science in data analytics distance learning, affordable master of science in data analytics",
    h1: "Master of Science in Data Analytics (Online)",
  },
  "master-of-science-in-finance": {
    title: "Online Master of Science in Finance | Recognised | UeCampus",
    description: "Study a recognised Master of Science in Finance 100% online with UeCampus. Flexible schedules, monthly instalments and full tutor support. Sept 2026",
    keywords: "online master of science in finance, recognised master of science in finance online, master of science in finance distance learning, affordable master of science in finance",
    h1: "Master of Science in Finance (Online)",
  },
  "mba-accounting-finance-eie": {
    title: "Online MBA Accounting Finance | eie Malta | UeCampus",
    description: "Accredited European MBA Accounting Finance delivered 100% online through eie European Business School. Flexible, affordable, globally recognised.",
    keywords: "online mba accounting finance, mba accounting finance eie european business school, european degree online, MQF accredited degree",
    h1: "MBA Accounting Finance - eie European Business School (Online)",
  },
  "mba-accounting-finance-ppa": {
    title: "Online MBA Accounting Finance | PPA Paris | UeCampus",
    description: "Study an accredited MBA Accounting Finance online with PPA Business School Paris. No GMAT, flexible payments, finish in 12-18 months. Enrolling for",
    keywords: "online mba accounting finance, mba accounting finance ppa business school, french business school mba accounting finance online, affordable mba accounting finance",
    h1: "MBA Accounting Finance - PPA Business School Paris (Online)",
  },
  "mba-general-management-walsh": {
    title: "Online MBA General Management | Walsh College USA | UeCampus",
    description: "Earn an accredited MBA General Management 100% online from Walsh College USA (HLC & ACBSP accredited). Flexible study, monthly instalments, Sept 2026",
    keywords: "online mba general management, mba general management walsh college, accredited american mba general management online, US degree online",
    h1: "MBA General Management - Walsh College, USA (Online)",
  },
  "mba-human-resource-management-ppa": {
    title: "Online MBA Human Resource Management | PPA Paris | UeCampus",
    description: "Study an accredited MBA Human Resource Management online with PPA Business School Paris. No GMAT, flexible payments, finish in 12-18 months. Enrolling",
    keywords: "online mba human resource management, mba human resource management ppa business school, french business school mba human resource management online, affordable mba human resource management",
    h1: "MBA Human Resource Management - PPA Business School Paris (Online)",
  },
  "mba-international-business-ppa": {
    title: "Online MBA International Business | PPA Paris | UeCampus",
    description: "Study an accredited MBA International Business online with PPA Business School Paris. No GMAT, flexible payments, finish in 12-18 months. Enrolling for",
    keywords: "online mba international business, mba international business ppa business school, french business school mba international business online, affordable mba international business",
    h1: "MBA International Business - PPA Business School Paris (Online)",
  },
  "mba-supply-chain-management-ppa": {
    title: "Online MBA Supply Chain Management | PPA Paris | UeCampus",
    description: "Study an accredited MBA Supply Chain Management online with PPA Business School Paris. No GMAT, flexible payments, finish in 12-18 months. Enrolling for",
    keywords: "online mba supply chain management, mba supply chain management ppa business school, french business school mba supply chain management online, affordable mba supply chain management",
    h1: "MBA Supply Chain Management - PPA Business School Paris (Online)",
  },
  "ms-information-technology-walsh": {
    title: "Online MS Information Technology | Walsh College | UeCampus",
    description: "Earn an accredited MS Information Technology 100% online from Walsh College USA (HLC & ACBSP accredited). Flexible study, monthly instalments, Sept 2026",
    keywords: "online ms information technology, ms information technology walsh college, accredited american ms information technology online, US degree online",
    h1: "MS Information Technology - Walsh College, USA (Online)",
  },
  "ms-management-walsh": {
    title: "Online MS Management | Walsh College USA | UeCampus",
    description: "Earn an accredited MS Management 100% online from Walsh College USA (HLC & ACBSP accredited). Flexible study, monthly instalments, Sept 2026 intake.",
    keywords: "online ms management, ms management walsh college, accredited american ms management online, US degree online",
    h1: "MS Management - Walsh College, USA (Online)",
  },
  "ms-marketing-walsh": {
    title: "Online MS Marketing | Walsh College USA | UeCampus",
    description: "Earn an accredited MS Marketing 100% online from Walsh College USA (HLC & ACBSP accredited). Flexible study, monthly instalments, Sept 2026 intake.",
    keywords: "online ms marketing, ms marketing walsh college, accredited american ms marketing online, US degree online",
    h1: "MS Marketing - Walsh College, USA (Online)",
  },
  "msc-artificial-intelligence-walsh": {
    title: "MSc Artificial Intelligence Online | Walsh | UeCampus",
    description: "Earn an accredited MSc Artificial Intelligence 100% online from Walsh College USA (HLC & ACBSP accredited). Flexible study, monthly instalments, Sept",
    keywords: "online msc artificial intelligence, msc artificial intelligence walsh college, accredited american msc artificial intelligence online, US degree online",
    h1: "MSc Artificial Intelligence - Walsh College, USA (Online)",
  },
  "msc-cyber-security-walsh": {
    title: "Online MSc Cyber Security | Walsh College USA | UeCampus",
    description: "Earn an accredited MSc Cyber Security 100% online from Walsh College USA (HLC & ACBSP accredited). Flexible study, monthly instalments, Sept 2026 intake.",
    keywords: "online msc cyber security, msc cyber security walsh college, accredited american msc cyber security online, US degree online",
    h1: "MSc Cyber Security - Walsh College, USA (Online)",
  },
  "msc-in-ai-and-machine-learning": {
    title: "Online MSc in AI and Machine Learning | UeCampus",
    description: "Study a recognised MSc in AI and Machine Learning 100% online with UeCampus. Flexible schedules, monthly instalments and full tutor support. Sept 2026",
    keywords: "online msc in ai and machine learning, recognised msc in ai and machine learning online, msc in ai and machine learning distance learning, affordable msc in ai and machine learning",
    h1: "MSc in AI and Machine Learning (Online)",
  },
  "phd-in-artificial-intelligence--machine-learning": {
    title: "PhD in Artificial Intelligence Machine Learning | UeCampus",
    description: "Study a recognised PhD in Artificial Intelligence Machine Learning 100% online with UeCampus. Flexible schedules, monthly instalments and full tutor",
    keywords: "online phd in artificial intelligence machine learning, recognised phd in artificial intelligence machine learning online, phd in artificial intelligence machine learning distance learning, affordable phd in artificial intelligence machine learning",
    h1: "PhD in Artificial Intelligence Machine Learning (Online)",
  },
  "phd-in-organizational-leadership": {
    title: "Online PhD in Organizational Leadership | UeCampus",
    description: "Study a recognised PhD in Organizational Leadership 100% online with UeCampus. Flexible schedules, monthly instalments and full tutor support. Sept 2026",
    keywords: "online phd in organizational leadership, recognised phd in organizational leadership online, phd in organizational leadership distance learning, affordable phd in organizational leadership",
    h1: "PhD in Organizational Leadership (Online)",
  },
  "qualifi-level-3-business-management": {
    title: "Level 3 Business Management Diploma Online | UeCampus",
    description: "Qualifi Level 3 Diploma in Business Management: Equivalent to A-Levels/Grade 12 and your bridge to university study. 100% online, no exams, flexible",
    keywords: "level 3 diploma in business management online, qualifi level 3 business management, level 3 business management qualification UK, online business management diploma",
    h1: "Qualifi Level 3 Diploma in Business Management (Online)",
  },
  "qualifi-level-3-integrated-business-management": {
    title: "Level 3 Integrated Business Management Diploma | UeCampus",
    description: "Qualifi Level 3 Diploma in Integrated Business Management: Equivalent to A-Levels/Grade 12 and your bridge to university study. 100% online, no exams",
    keywords: "level 3 diploma in integrated business management online, qualifi level 3 integrated business management, level 3 integrated business management qualification UK, online integrated business management diploma",
    h1: "Qualifi Level 3 Diploma in Integrated Business Management (Online)",
  },
  "qualifi-level-4-accounting-finance": {
    title: "Level 4 Accounting Finance Diploma Online | UeCampus",
    description: "Qualifi Level 4 Diploma in Accounting Finance: Equivalent to the first year of a UK degree. Study 100% online with assignments only and progress towards",
    keywords: "level 4 diploma in accounting finance online, qualifi level 4 accounting finance, level 4 accounting finance qualification UK, online accounting finance diploma",
    h1: "Qualifi Level 4 Diploma in Accounting Finance (Online)",
  },
  "qualifi-level-4-business-management": {
    title: "Level 4 Business Management Diploma Online | UeCampus",
    description: "Qualifi Level 4 Diploma in Business Management: Equivalent to the first year of a UK degree. Study 100% online with assignments only and progress towards",
    keywords: "level 4 diploma in business management online, qualifi level 4 business management, level 4 business management qualification UK, online business management diploma",
    h1: "Qualifi Level 4 Diploma in Business Management (Online)",
  },
  "qualifi-level-4-cyber-security": {
    title: "Level 4 Cyber Security Diploma Online | UeCampus",
    description: "Qualifi Level 4 Diploma in Cyber Security: Equivalent to the first year of a UK degree. Study 100% online with assignments only and progress towards a",
    keywords: "level 4 diploma in cyber security online, qualifi level 4 cyber security, level 4 cyber security qualification UK, online cyber security diploma",
    h1: "Qualifi Level 4 Diploma in Cyber Security (Online)",
  },
  "qualifi-level-4-information-technology": {
    title: "Level 4 Information Technology Diploma Online | UeCampus",
    description: "Qualifi Level 4 Diploma in Information Technology: Equivalent to the first year of a UK degree. Study 100% online with assignments only and progress",
    keywords: "level 4 diploma in information technology online, qualifi level 4 information technology, level 4 information technology qualification UK, online information technology diploma",
    h1: "Qualifi Level 4 Diploma in Information Technology (Online)",
  },
  "qualifi-level-4-psychology": {
    title: "Level 4 Psychology Diploma Online | UeCampus",
    description: "Qualifi Level 4 Diploma in Psychology: Equivalent to the first year of a UK degree. Study 100% online with assignments only and progress towards a full",
    keywords: "level 4 diploma in psychology online, qualifi level 4 psychology, level 4 psychology qualification UK, online psychology diploma",
    h1: "Qualifi Level 4 Diploma in Psychology (Online)",
  },
  "qualifi-level-5-accounting-finance": {
    title: "Level 5 Accounting Finance Diploma Online | UeCampus",
    description: "Qualifi Level 5 Diploma in Accounting Finance: Fast-track to the final year of a bachelors. UK Level 5 award, fully online, assignment-based with",
    keywords: "level 5 diploma in accounting finance online, qualifi level 5 accounting finance, level 5 accounting finance qualification UK, online accounting finance diploma",
    h1: "Qualifi Level 5 Diploma in Accounting Finance (Online)",
  },
  "qualifi-level-5-cyber-security": {
    title: "Level 5 Cyber Security Diploma Online | UeCampus",
    description: "Qualifi Level 5 Diploma in Cyber Security: Fast-track to the final year of a bachelors. UK Level 5 award, fully online, assignment-based with flexible",
    keywords: "level 5 diploma in cyber security online, qualifi level 5 cyber security, level 5 cyber security qualification UK, online cyber security diploma",
    h1: "Qualifi Level 5 Diploma in Cyber Security (Online)",
  },

  "qualifi-level-5-extended-business-management": {
    title: "Level 5 Extended Business Management Diploma | UeCampus",
    description: "Qualifi Level 5 Diploma in Extended Business Management: Fast-track to the final year of a bachelors. UK Level 5 award, fully online, assignment-based",
    keywords: "level 5 diploma in extended business management online, qualifi level 5 extended business management, level 5 extended business management qualification UK, online extended business management diploma",
    h1: "Qualifi Level 5 Diploma in Extended Business Management (Online)",
  },
  "qualifi-level-5-hospitality-tourism": {
    title: "Level 5 Hospitality Tourism Diploma Online | UeCampus",
    description: "Qualifi Level 5 Diploma in Hospitality Tourism: Fast-track to the final year of a bachelors. UK Level 5 award, fully online, assignment-based with",
    keywords: "level 5 diploma in hospitality tourism online, qualifi level 5 hospitality tourism, level 5 hospitality tourism qualification UK, online hospitality tourism diploma",
    h1: "Qualifi Level 5 Diploma in Hospitality Tourism (Online)",
  },
  "qualifi-level-5-information-technology": {
    title: "Level 5 Information Technology Diploma Online | UeCampus",
    description: "Qualifi Level 5 Diploma in Information Technology: Fast-track to the final year of a bachelors. UK Level 5 award, fully online, assignment-based with",
    keywords: "level 5 diploma in information technology online, qualifi level 5 information technology, level 5 information technology qualification UK, online information technology diploma",
    h1: "Qualifi Level 5 Diploma in Information Technology (Online)",
  },
  "qualifi-level-5-psychology": {
    title: "Level 5 Psychology Diploma Online | UeCampus",
    description: "Qualifi Level 5 Diploma in Psychology: Fast-track to the final year of a bachelors. UK Level 5 award, fully online, assignment-based with flexible",
    keywords: "level 5 diploma in psychology online, qualifi level 5 psychology, level 5 psychology qualification UK, online psychology diploma",
    h1: "Qualifi Level 5 Diploma in Psychology (Online)",
  },
  "qualifi-level-7-data-science": {
    title: "Level 7 Data Science Diploma Online | UeCampus",
    description: "Qualifi Level 7 Diploma in Data Science: A masters-level UK award and affordable route to an MBA/MSc top-up. Fully online, assignment-based, no exams.",
    keywords: "level 7 diploma in data science online, qualifi level 7 data science, level 7 data science qualification UK, online data science diploma",
    h1: "Qualifi Level 7 Diploma in Data Science (Online)",
  },
  "qualifi-level-7-hospitality-tourism-management": {
    title: "Level 7 Hospitality Tourism Management Diploma | UeCampus",
    description: "Qualifi Level 7 Diploma in Hospitality Tourism Management: A masters-level UK award and affordable route to an MBA/MSc top-up. Fully online",
    keywords: "level 7 diploma in hospitality tourism management online, qualifi level 7 hospitality tourism management, level 7 hospitality tourism management qualification UK, online hospitality tourism management diploma",
    h1: "Qualifi Level 7 Diploma in Hospitality Tourism Management (Online)",
  },
  "qualifi-level-7-human-resource-management": {
    title: "Level 7 Human Resource Management Diploma Online | UeCampus",
    description: "Qualifi Level 7 Diploma in Human Resource Management: A masters-level UK award and affordable route to an MBA/MSc top-up. Fully online, assignment-based",
    keywords: "level 7 diploma in human resource management online, qualifi level 7 human resource management, level 7 human resource management qualification UK, online human resource management diploma",
    h1: "Qualifi Level 7 Diploma in Human Resource Management (Online)",
  },
  "qualifi-level-7-information-technology": {
    title: "Level 7 Information Technology Diploma Online | UeCampus",
    description: "Qualifi Level 7 Diploma in Information Technology: A masters-level UK award and affordable route to an MBA/MSc top-up. Fully online, assignment-based, no",
    keywords: "level 7 diploma in information technology online, qualifi level 7 information technology, level 7 information technology qualification UK, online information technology diploma",
    h1: "Qualifi Level 7 Diploma in Information Technology (Online)",
  },
  "qualifi-level-7-psychology": {
    title: "Level 7 Psychology Diploma Online | UeCampus",
    description: "Qualifi Level 7 Diploma in Psychology: A masters-level UK award and affordable route to an MBA/MSc top-up. Fully online, assignment-based, no exams.",
    keywords: "level 7 diploma in psychology online, qualifi level 7 psychology, level 7 psychology qualification UK, online psychology diploma",
    h1: "Qualifi Level 7 Diploma in Psychology (Online)",
  },
  "qualifi-level-7-strategic-management": {
    title: "Level 7 Strategic Management Diploma | MBA Route | UeCampus",
    description: "Masters-level Level 7 Diploma in Strategic Management & Leadership - the fast, affordable MBA top-up route. 100% online, assignments only.",
    keywords: "level 7 diploma in strategic management and leadership, MBA top up level 7, level 7 diploma equivalent to masters, qualifi strategic management",
    h1: "Qualifi Level 7 Diploma in Strategic Management and Leadership",
  },
  "qualifi-level-7-strategic-marketing": {
    title: "Level 7 Strategic Marketing Diploma Online | UeCampus",
    description: "Qualifi Level 7 Diploma in Strategic Marketing: A masters-level UK award and affordable route to an MBA/MSc top-up. Fully online, assignment-based, no",
    keywords: "level 7 diploma in strategic marketing online, qualifi level 7 strategic marketing, level 7 strategic marketing qualification UK, online strategic marketing diploma",
    h1: "Qualifi Level 7 Diploma in Strategic Marketing (Online)",
  },
  "stem-mba": {
    title: "Online STEM MBA | Recognised | UeCampus",
    description: "Study a recognised STEM MBA 100% online with UeCampus. Flexible schedules, monthly instalments and full tutor support. Sept 2026 intake open.",
    keywords: "online stem mba, recognised stem mba online, stem mba distance learning, affordable stem mba",
    h1: "STEM MBA (Online)",
  },
};
